func new --name transfer-funds --template "Durable Functions orchestrator"
func new --name read-input --template "Durable Functions activity"
func new --name validate-input --template "Durable Functions activity"
func new --name transfer-funds --template "Durable Functions activity"
func new --name start-from-http --template "Durable Functions HTTP starter" --authlevel "anonymous"
